apiVersion: v1
data:
    password: ENC[AES256_GCM,data:O9y7lYz1EHeh8l6c,iv:/9AXH0R4SCWyQ3EiciwadlkANapys7yMuqjASzEDrkk=,tag:O7uOmOp5fK+7DJhIx/A0rA==,type:str]
    url: ENC[AES256_GCM,data:wuRRI5GOyEDTr0TKh8dqUipq9xUJm62YmUa/QM8sFi6Ewv5eO110+0BaqGKv2ETLzh4VK4lJljTL8xti,iv:FPKzerLfg/GBjdY99QzabaP3cdQnwkkIMi4LlIjEjc4=,tag:vFU1coHIXPEq4r8MCk1Jpg==,type:str]
    user: ENC[AES256_GCM,data:pal/JvMPt2DBEQ+8,iv:LeW1BNL0Fo4/ZyRoHqH54pyeb8MLp/hjHUUdHCND6Iw=,tag:mPNkf19cXaFE+TSWbilYJw==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: ostock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOUFBdEVuZmw5TTdXL2lX
            T29SbWtNKzVEdFZmckZnWU92VXc4Z3JPdURNClpRU3ppNkg1S0FNblBDckFFVmJ6
            bXJhQ2pEUTJ2eGJ2STdTNXNPVkEwRFUKLS0tIDk4WXJXOGtjSEhRRUVCMndyMTVY
            TEhiemJRTnZKbmU0WmRndHZwQVRiaGcK1W4DRx+BKCMuPLUAHmTYtqTOmxnR2Jg7
            BHdLywPGNgYHyMbtWvMej84da9EkpjdU4KVCclJnQZ3b+ITeOdc7/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T13:42:15Z"
    mac: ENC[AES256_GCM,data:DEkaC+X9buWP3MRAJynezxX1tSgzh5tuBxGuehvRnMkJ0CQhwiRzEna5gqv6KmBrUlTlWDypTE1FrIxoKr08nzMscl7WSJuCw3t/7S/6T/t+GRPxWiY88HXhGdG8ALuO+72LCijhB21BsUOyZJZYZJmYyal+4eL/YxDFi44h1IQ=,iv:M4cUUpba7E0FTFv2DtzQ7DRBlkaIkc7QEaTBx3H+c1c=,tag:rMmJ56ISIV9gPYVvGkVTKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
