apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Ci/g4FmF58hxhNpRGFZ9zGXzXCJ64zxz,iv:0EtmzB5rvGjK9G1dbHu49rB5AvP7S+Nz0ppt6C3ALgI=,tag:Hmmx9zqjIJkYG9/S1A6IXg==,type:str]
    url: ENC[AES256_GCM,data:PoNuUufNn4NbJlsHd2XgnUIviMtpFepZNwaYoA1hTkmUGqpIsIcojCEm9uyLAvxKB1oYNg==,iv:3Nfl396ZNlcl3kP7FZzlQn6bodpfKvNU1h9lRtJ9oRk=,tag:9B80pHwMdENH+qXlDLXBVg==,type:str]
    user: ENC[AES256_GCM,data:JKdtEjqXSLLbYwuH,iv:00nrZboPBPgh2bqyDv4BDiOGW9CgyXyBJZYC2tIGZl8=,tag:J1GuVWX/HAL/H4XEAnnzxQ==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: ostock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UE1jUldXMFZucmxWamVD
            YnA5aHRxUVBnL2lYNXdsOEhSaW5oZTd1TmpvCmRKQUFKK2pNdWRsdTdnbXRwd3Q3
            SnRiTUhUU2ErRUdtZkRTUEhVOGszNUEKLS0tIDVPakNEUFBYRUZEa2pyZ3dwdjFY
            OXNXUXo2cys0OW1paHlYajJuQi9FMG8K6gdPWlkAP1J0lXNM+vWU5cagjGwx+Bsf
            +VMHSp8Gh/J47shmGDX/73VxR982/IfwtFYpEprAKamfm/asmhwvow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T01:04:54Z"
    mac: ENC[AES256_GCM,data:gjT7WE4xk3amD7fIjzH0a6hl1P968amQIKi+VUV00N6mhZrflrcRP5jV5kzKQjX/ZRpknXDdxMeoExoV+CltN2JN1PfgyE0MMOmqh+zDip0qSQwepSxG/d0fvwc84TPw7C2x+wgjYluFDRQPzSGbQ/045Qclbg1db4aRoQtPLDA=,iv:kpteMFwqqHC5oa/XwM7Nq8kZNEQ8g9OL+P0u7TLZqsA=,tag:h2pLhcwOVhwYQgV4qJ4bmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
