apiVersion: v1
data:
    password: ENC[AES256_GCM,data:6ziEyFLKtPW/tyYl60vJFG4i6MX5p+eS,iv:YZvEbj/sqI54Vqwnzh9yJHBjTYZLcPp6TSNoPGWw9mg=,tag:tBtceXsRFu8eO+03/PyKdg==,type:str]
    url: ENC[AES256_GCM,data:GrQG9Yq6oBPPmhRSIUYISijWqa2iM0c0Miszv4LWuvILR2chESCOq04kKXigQ3ce+JqVoLIrAZaYokYCBdAAbw==,iv:QM/loZb8onGuYUAnJk1P7nNpC8G5vkDii8VRUuv8U0M=,tag:rqn5rhlAmAB2kT5wPxLEGA==,type:str]
    user: ENC[AES256_GCM,data:q3Xa3MI/8CEgXFFa,iv:ucNlXF6CUkdaeACgjteAbqaTK3IJpzo9hGJtyFwo0bs=,tag:nXEbNKfNqj3Tr90aRnI2qg==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: ostock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaFdWSGVHN1c1dmVWSjNh
            UFF3SE5iOWxKODkwdmdaOG5FblB1WEJTV2lNCmpaeU1oZ2psM1l4ZitoQVZyQUdo
            b3RMTHAxU0pZeU9kQmVnSkQ0R2tKQW8KLS0tIDlEaDMvaEYwbE1qRnBHdGNpQVFw
            UzB4RXR0Y05GRnNXdFkvWnhhWmFmTHcKOLpyVxxkkTjX9B4VlQ6j1gdQaSzGREFz
            Us77Dq09Naa+h/qUptKD4UAZvzBU5wN94g+6AxSmzWKLnOEDkiZ6Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T02:12:19Z"
    mac: ENC[AES256_GCM,data:BLcMt0KHmWqQAH8IgWhd2T56+7XNEmplPmrN5Q2xa670SCTh4ZWx5VV2ov5dAAws7XT+5SIQw7q7ubnRXPfXQkAzSZldQZH+eX/XRH5d2By1/eA+C3MPSFr7U1SSLpYmQE+ldhBQntrqHt4EeVE+kHirQufOE6iWui6viRYbs5I=,iv:fmh81B9PIpF7QNOYB/xI8sk4ND5UFgB9m2/tEmwzcHY=,tag:BBPVWKxigWR2k92jYiMM3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
